#!/bin/bash
source "$(dirname "$0")/set_env.sh"

ROOT_DIR=$(dirname "$(realpath $0)")/..
export RUST_DIR=$ROOT_DIR/src/rust
export COMPONENT_DIR=$ROOT_DIR/$MOPS_DIR/component
echo "NOTE: This script may fail when run in Motoko's development nix-shell, which uses an old version of cargo/rustc."
echo "      If this happens, run it in a separate shell with your regular Rust development setup."

build_rust_component() {
  component_name=$1
  # Rust-conventions:
  #   * WASMs generated by cargo build use underscores in their names
  # WIT/WAC-conventions:
  #   * the component name must use hyphens as separators (not underscores)
  #   * imported components must use naming `package_name:module-name`
  #   * importing `component:foo-bar` expects binary `foo-bar.wasm` in folder `component`
  #   * if folder `component` contains both `foo-bar.wasm` and a subfolder `foo-bar`, WAC gets confused...
  # Motoko-conventions:
  #   * importing `foo-bar` expects a file lib.mo in folder `foo-bar` (i.e. foo-bar.mo would not work)
  #
  # Hence, the layout in mops:
  # - all components are in subfolder mops/component/
  # - component `foo-bar` contributes the following:
  #   * a subfolder mops/component/foo_bar (with underscore), containing file lib.mo
  #   * a WASM file: mops/component/foo-bar.wasm
  wac_compatible_component_name=$(echo "$component_name" | tr '_' '-')

  echo --- Building Rust component $component_name to target/${component_name}.wasm
  cd $RUST_DIR/$component_name || exit
  cargo build --$BUILD_MODE --target $TARGET &&
  wasm-tools component new target/$TARGET/$BUILD_MODE/${component_name}.wasm -o target/${component_name}.wasm &&
  echo ... Copying to mops-dir $COMPONENT_DIR/${component_name}@0.0.1
  mkdir -pv "$COMPONENT_DIR/$component_name@0.0.1"
  cp target/${component_name}.wasm $COMPONENT_DIR/${wac_compatible_component_name}.wasm
  cp ${component_name}.mo $COMPONENT_DIR/${component_name}@0.0.1/lib.mo
  echo ... DONE building $component_name
}

(
  echo ___ Building Rust components...
  build_rust_component ic_sig_verifier
  build_rust_component meet_and_greet
  build_rust_component zstd
  echo ___ DONE building Rust components.
)
