pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=build / tests (ubuntu-latest) (pull_request)
      - status-success=build / tests (macos-latest) (pull_request)
      - base=master
      - label=automerge-squash
    actions:
      merge:
        method: squash
        strict: smart
        commit_message: title+body
      delete_head_branch: {}
  - name: Automatic closing succesfull trials
    conditions:
      - status-success=build / tests (ubuntu-latest) (pull_request)
      - status-success=build / tests (macos-latest) (pull_request)
      - label=autoclose
    actions:
      close:
        message: CI looks good, this dependency bump would not cause problems, hence closing this trial PR.
      delete_head_branch: {}
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
        - automerge-squash
        - autoclose
  - name: Auto-approve auto-PRs
    conditions:
      - author=dfinity-bot
      - label=automerge-squash
    actions:
      review:
        type: APPROVE
        message: This bot trusts that bot
  - name: Auto-approve changelog/release PR
    conditions:
      - files=Changelog.md
      - "#files=1"
      - label=automerge-squash
    actions:
      review:
        type: APPROVE
        message: A change to Changelog.md? I can handle that!
