pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=hydra:dfinity-ci-build:evaluation
      - status-success=hydra:dfinity-ci-build:motoko:all-systems-go
      - base=master
      - label=automerge-squash
    actions:
      merge:
        method: squash
        strict: smart
        commit_message: title+body
      delete_head_branch: {}
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
        - automerge
        - automerge-squash
        - automerge-rebase
  - name: Auto-approve auto-PRs
    conditions:
      - author=dfinity-bot
    actions:
      review:
        type: APPROVE
        message: This bot trusts that bot
