pull_request_rules:
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
          - automerge-squash
  - name: Auto-approve auto-PRs
    conditions:
      - author=pr-automation-bot-public[bot]
      - label=automerge-squash
    actions:
      review:
        type: APPROVE
        message: This bot trusts that bot
    actions:
      review:
        type: APPROVE
        message: A change to `doc/docusaurus/package-lock.json`? I can handle that!
      label:
        add:
          - automerge-squash
