= Motoko Programming Language Guide
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:platform: Internet Computer blockchain network
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:!page-repl:

== About this guide

The _{proglang} Programming Language Guide_ introduces key features of the general-purpose {proglang} programming language and provides examples and reference information to help you learn the nuances of the language and the practical implications of how to apply it.

The {proglang} programming language is optimized for developing programs that run on the {platform} and to work with the {sdk-long-name}.
You could, in principle, also write programs using {proglang} for more traditional platforms and to run in other contexts, though support for this is currently best-effort and incomplete.
This guide attempts to strike a balance between highlighting features that are uniquely suited to running on the {IC} and features that are generally-applicable or well-suited for programs running on all targets.

== Intended audience

This guide provides reference information and examples for programmers who want to explore or plan to use the {proglang} programming language.
Most of the information in this guide is applicable independent of whether you are developing programs to run on the {IC} or working with the {sdk-short-name}.

The guide assumes you are familiar with basic programming principles and terminology and have at least some experience writing programs in a high-level programming language such as C++ or Rust, or have practical experience working with a scripting language such as JavaScript or TypeScript.
In addition, {proglang} incorporates some aspects of functional programming, so you might find some knowledge of functional programming design principles helpful in learning to use {proglang}.

Although this guide is intended to help readers from different backgrounds understand the basic design principles and semantics of the {proglang}, you should keep in mind that the language implementation and the documentation are also continuing to evolve.

== Using this guide

To provide a framework for learning {proglang}, you might want to start by reviewing <<engineering-values-and-goals>>.
The <<engineering-values-and-goals>> describe the core design considerations for the development and evolution of the {proglang} programming language.

With those considerations in mind, you can start to explore fundamental concepts, including the role of types and type annotations, in simple code examples and small programs.

Once you are familiar with the basic concepts and terminology, later sections introduce programs that compute in more interesting ways, including function abstractions, user-defined type definitions, user-defined actors, and asynchronous communication.

As you begin using {proglang} to write your own programs, you can return to this guide for reference information and examples.

Most of the code examples in this guide are interactive: you can live edit the example, interpret the code in the browser and see the result. The interpreter is provided for education purposes. While most of the language features are supported in the interpreter, they are not exactly the same as the real compiler. For example, you may get a stack overflow for a medium-size input, while the real compiler handles the input just fine. Some of the system features are not fully supported, such as cycles, canister imports and state-mutating query calls.

== Documentation conventions

The following conventions are used in this guide:

- `+Fixed-width+` font is used for sample code, program names, program output, file names, and commands that you type at the command line.
- **Bold** text is used to emphasize commands, buttons, or user interface text, and to introduce new terms.
- _Italics_ are used for book titles and to emphasize specific words or terms.
- The CAUTION style is used to indicate content that is missing or incomplete.
- The WARNING style is used to indicate where content is outdated or potentially inaccurate.
- The NOTE style is used to indicate content that describes a feature that is not yet supported but is planned for a future release.

[#engineering-values-and-goals]
== Engineering values and goals

The engineering effort behind the design and implementation of {proglang} is driven by a core set of values and goals.
The {company-id} engineering organization uses these values and goals to define and prioritize the language features and enhancements to add and improve as part of _ongoing_ language development.

For transparency into the principles that guide the engineering effort, the engineering organization  has identified the following sets of core values and secondary values for driving the direction of the{proglang} programming language.

=== Core values

The following guiding principles represent the core values of the engineering organization in prioritized order:

. Seamless integration with the link:../../../../concepts/what-is-IC{outfilesuffix}#what-is-the-internet-computer[{IC} blockchain network] to ensure that {proglang} provides full language support for the actor-based model, asynchronous messaging, data persistence, interface description language interoperability, and other features.
. Ergonomics to ensure that {proglang} embraces familiarity, simplicity, clarity, explicitness, and other human factors.
. Formal correctness to ensure that {proglang} maintains state isolation, a sound type system and type safety, precision, pattern matching, appropriate defaults, and coding best-practices.

=== Secondary values

The following principles represent the secondary values of the engineering organization that are deemed important but not primary driving factors:

. Expressiveness, so that {proglang} provides first-class functions, polymorphism, pattern matching, and more as the language evolves.
. Performance, so that {proglang} provides reasonably fast operation initially and continues to improves as the language evolves.
. Readiness, so the {proglang} comes with "batteries included" in the form of libraries and examples and out-of-the-box integration with the {sdk-short-name}.

=== Non-goals

As a counterpoint to the core values and goals, the engineering organization also identified the following as "non-goals" that are outside of the scope of the engineering effort:

. Having a more advanced type system, with cutting-edge features.
. Simplicity over functionality in design or implementation (the "Worse is Better" approach).
. Interoperability or support for running {proglang} programs on blockchains other than the {IC}.

== Finding more information

For information about using {proglang} with the {sdk-short-name}, see the link:../../index{outfilesuffix}[SDK Developer Tools].

For background information on various topics relevant to the design, use, or deployment of {proglang} services, or the language's design itself, consider the following resources as a starting point:

[#webassembly]
=== WebAssembly

- https://webassembly.org/[WebAssembly home page].
- https://www.youtube.com/watch?v=fvkIQfRZ-Y0[WebAssembly overview video (youtube)].

[#modern-type-systems]
=== Modern type systems

 - link:++http://www.cs.cmu.edu/~rwh/pfpl/++[Practical Foundations for Programming Languages]
   by Robert Harper. Cambridge University Press, 2016.
 - link:++https://www.cis.upenn.edu/~bcpierce/tapl/++[Types and Programming Languages]
   by Benjamin C. Pierce. The MIT Press.

== Getting additional support

If you are looking for more information or technical support, the {company-id} website provides quick access to frequently-asked questions, technical articles, developer updates, and other resources.
From the website, you can search knowledge base articles, open and view support cases, sign up for the newsletter, read the latest blog posts, view how-to videos, download software updates, or exchange ideas with members of the community.

In addition to the resources available on the website, you can connect with {company-id} or other developers using social media or by visiting the {company-id} Community Forum on Discourse and joining the conversation.
