= Imperative control flow

Control flow comes in two flavors
- _declarative_ when the value itself guides control and the selection of the resulting value, like in `if` and `switch` expressions
- _imperative_ (or programmer designed), where control changes according to some manipulative syntax and the result value either doesn't exist or is uninteresting.

Imperative control flow often goes hand-in-hand with destructive updates (value-changing assignments) or other types of side-effects like input/output.

[[early-return]]
== Early `return` from `func`

Normally, the result of a function is the value of the last expression in its body. Sometimes the result is readily available at an earlier moment (usually due to some checked condition), and in such situations the `return <val>` construct can be used to abandon the regular control flow, and give the function a result immediately.

to do:

 - discuss labels and labeled gotos
 - discuss use of `for` loops
 - discuss iterators; discuss examples of iterating an array and iterating a text value (`.keys`, `.vals`, `.chars`, `.size`, etc.)
 - discuss use of `while` loops
 - discuss use of `do` loops

[[intro-range]]
== Using `range` with a `for` loop

The `range` function produces an iterator (of type `Iter`) with the given lower and upper bound, inclusive.

The following loop example prints the numbers `0` through `10` over its _eleven_ iterations:

....
var i = 0;
for (j in range(0, 10)) {
 printNat(j);
 assert(j == i);
 i += 1;
};
assert(i == 11);
....


More generally, the function `range` is a `class` that constructs iterators over sequences of natural numbers.  Each such iterator has type `Iter<Nat>`.

As a constructor function, `range` has a function type:

....
(lower:Nat, upper:Nat) -> Iter<Nat>
....

Where `Iter<Nat>` is an iterator object type with a `next` method that produces optional elements, each of type `?Nat`:

....
type Iter<Nat> = {next : () -> ?Nat};
....

For each invocation, `next` returns an optional element (of type
`?Nat`).

The value `null` indicates that the iteration sequence has terminated.

Until reaching `null`, each non-`null` value, of the form ``?``__n__ for some number _n_, contains the next successive element in the iteration sequence.

[[intro-revrange]]
== Using `revrange`

Like `range`, the function `revrange` is a `class` that constructs iterators (each of type `Iter`).
As a constructor function, it has a function type:

....
(upper:Nat, lower:Nat) -> Iter
....

Unlike `range`, the `revrange` function _descends_ in its iteration sequence, from an initial _upper_ bound to a final _lower_ bound.
