= Language Quick Reference
:proglang: Motoko
:sdk-short-name: DFINITY Canister SDK
:company-id: DFINITY

////
TODO
* [ ] Various inline TBCs and TBRs and TODOs
* [ ] Typing of patterns
* [ ] Prelude
* [ ] Modules and static restriction
* [ ] Prelude (move scattered descriptions of assorted prims like charToText here)
* [ ] Prose description of definedness checks
* [ ] Platform changes: remove async expressions (and perhaps types); restrict await to shared calls.
////

This section serves as a technical reference for the {proglang} programming language and the examples provided in the _{proglang} Programming Language Guide_.
It include formal definitions for all language features.  

== What's covered and who it's for

In addition to basic reference information for general purposes and for programmers without any specialized knowledge, the _{proglang} Quick Reference_ includes specific technical details of interest to specialized audiences, including:

* Contributors responsible for providing the higher-level documentation about features and usage of the {proglang} programming language.
* Compiler experts interested in the details of {proglang} and its compiler.
* Advanced programmers who want to learn more about the lower-level details of {proglang}.

The language quick reference is intended to provide complete reference information about {proglang}, but in abbreviated format.
Therefore, you should not use this reference if you are looking for a general introduction to using {proglang, explanatory text about language features, sample code, or scenario-based usage examples.
For a less formal but more usage-based discussion of {proglang} and specific {proglang} features, see the link:motoko{outfilesuffix}[_{proglang} Language Guide_].

== Interpreting the notation used 

This quick reference describes many aspects of the {proglang} programming language using Backus–Naur Form (BNF) notation.
The link:https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[Backus–Naur form (BNF)] notation is often used to describe language grammars and generally takes the following form:

....
<identifier> ::= expression 
....

As illustrated in this example, the BNF notation uses the colon-colon-equals (`+::=+`) separator. In most cases, you can interpret the `+::=+` separator to mean "is defined as" or "is constructed from" when describing a language. 
Therefore, this notation indicates that the specified `+<identifier>+` is defined as (or is constructed from) the specified `+expression+`.
