= Message Inspection
:proglang: Motoko
:company-id: DFINITY


On the {IC}, a canister can selectively
https://smartcontracts.org/docs/current/references/ic-interface-spec/#ingress-message-inspection[inspect and decline] ingress messages submitted through the https interface:


> A canister can inspect ingress messages before executing them. When the IC receives an update call from a user, the IC will use the canister method `canister_inspect_message` to determine whether the message shall be accepted.
> If the canister is empty (i.e. does not have a Wasm module), then the ingress message will be rejected.
> If the canister is not empty and does not implement `canister_inspect_message`, then the ingress message will be accepted.
>
> In `canister_inspect_message`, the canister can accept the message by invoking
`ic0.accept_message : () -> ()`.
> This function traps if invoked twice.
> If the canister traps in `canister_inspect_message` or does not call `ic0.accept_message`, then the access is denied.
>
> NOTE: The `canister_inspect_message` is _not_ invoked for query calls, inter-canister calls or calls to the management canister.
> -- IC Interface specification

In {proglang}, actors can elect to inspect and accept or deny ingress messages by declaring a particular `system` function called `inspect_message`.
Given a record of message attributes, this function produces a `Bool` that indicates whether to accept or deny the message by returning `true` or `false`.
The function is invoked (by the system) on each ingress message. Similar to a query, any side-effects of an invocation are discarded and transient.
A call that traps due to some fault has the same result as returning `false` (message denial).

Unlike other system functions, that have a fixed argument type, the argument type of `inspect_message` depends on the interface of the enclosing actor.
In particular, the formal argument of `inspect_message` is a record that contains fields of the following types.

* `caller : Principal`: the principal, possibly anonymous, of the caller of the method.

* `arg : Blob` : the raw, binary content of the message argument.

* `msg : {...; #name: () -> T; ...}` : a variant of decoding functions, one per shared function of the actor called `name`, carrying a function that, when applied to a unit value `()`,
  returns the decoded arguments of that function as a value of (argument) type `T`.

Using a variant, tagged by method name, allows the return type, `T`, of the decoding function to vary with the name, `name`, of the shared function.

Exploiting {proglang}'s subtyping, the formal argument can omit record fields it does not require, or selectively ignore the arguments of particular shared functions, for example,
in order to simply dispatch on the name of a function without inspecting its actual argument.

WARNING: An actor that fails to declare system method `inspect_message` will simply accept all ingress messages.

A simple, contrived example is a counter actor, that inspects some of its messages in detail, and others only superficially:

[source,motoko]
----
include::../examples/InspectFull.mo[]
----

Note that, due to subtyping, all of the following variations, in order of increasing argument specificity, are legal definitions of `inspect_message`.

Blanket denial of all ingress messages, ignoring further information:

[source,motoko]
----
include::../examples/InspectNone.mo[tag=inspect-none]
----

Denying anonymous calls:

[source,motoko]
----
include::../examples/InspectCaller.mo[tag=inspect-caller]
----

Denying large messages, based on argument's size (in bytes).

[source,motoko]
----
include::../examples/InspectArg.mo[tag=inspect-arg]
----

Denying messages by name only, ignoring message arguments (note the use
of type `Any` as message argument variants):

[source,motoko]
----
include::../examples/InspectName.mo[tag=inspect-name]
----

A combination of the previous three, specifing the argument types of some variants while ignoring others at type `Any` and using
pattern matching to conflate identical cases.

[source,motoko]
----
include::../examples/InspectMixed.mo[tag=inspect-mixed]
----


TIP: Implementing `inspect_message` after the fact, once all shared functions of an actor have already been implemented can be tedious if you want to declare a variant for each shared function.
A simple trick is to first implement the method incorrecty, with a `()` argument, and then use the compiler's corresponding error message to construct the required argument type for you.