= Message Inspection
:proglang: Motoko
:company-id: DFINITY


On the {IC}, a canister can selectively
_inspect_ and _accept_ or _decline_ ingress messages submitted through the HTTP interface:


> A canister can inspect ingress messages before executing them. When the IC receives an update call from a user, the IC will use the canister method `canister_inspect_message` to determine whether the message shall be accepted.
> If the canister is empty (i.e. does not have a Wasm module), then the ingress message will be rejected.
> If the canister is not empty and does not implement `canister_inspect_message`, then the ingress message will be accepted.
>
> In `canister_inspect_message`, the canister can accept the message by invoking
`ic0.accept_message : () -> ()`.
> This function traps if invoked twice.
> If the canister traps in `canister_inspect_message` or does not call `ic0.accept_message`, then the access is denied.
>
> NOTE: The `canister_inspect_message` is _not_ invoked for HTTP query calls, inter-canister calls or calls to the management canister.
> NOTE:  Confusingly, a `shared query` function _can_ be called using a regular HTTP call to obtain a certified response: this is why the variant type also includes `shared query` functions.
> -- https://smartcontracts.org/docs/current/references/ic-interface-spec/#ingress-message-inspection[IC Interface Specification]

Message inspection mitigates some denial of service attacks,
designed to drain canisters of cycles by placing unsolicited free calls.

REMARK: You can think of `inspect_message` as providing the "Collect call from <name>. Do you accept charges?" prologue of an old-fashioned, operator-assisted, collect phone call.

In {proglang}, actors can elect to inspect and accept or decline ingress messages by declaring a particular `system` function called `inspect_message`.
Given a record of message attributes, this function produces a `Bool` that indicates whether to accept or decline the message by returning `true` or `false`.
The function is invoked (by the system) on each ingress message. Similar to a query, any side-effects of an invocation are discarded and transient.
A call that traps due to some fault has the same result as returning `false` (message declination).

Unlike other system functions, that have a fixed argument type, the argument type of `inspect_message` depends on the interface of the enclosing actor.
In particular, the formal argument of `inspect_message` is a record of fields of the following types:

* `caller : Principal`: the principal, possibly anonymous, of the caller of the message;
* `arg : Blob` : the raw, binary content of the message argument;
* `msg : <variant>` where `<variant> == {...; #<id>: () -> T; ...}` is a variant of _decoding_ functions,
   one per shared function, '<id>', of the actor. The  `msg` arguments contains a function that, when applied, returns the (decoded) argument of function `<id>` as a value of type `T`.

Using a variant, tagged with `#<id>`, allows the return type, `T`, of the decoding function to vary with the identifier, `<id>`, of the shared function.

The variant's arguments are functions so that one can avoid the expense of message decoding (when appropriate).

Exploiting subtyping, the formal argument can omit record fields it does not require, or selectively ignore the arguments of particular shared functions, for example,
in order to simply dispatch on the name of a function without inspecting its actual argument.

WARNING: An actor that fails to declare system field `inspect_message` will simply accept all ingress messages.

A simple, contrived example is a counter actor, that inspects some of its messages in detail, and others only superficially:

[source,motoko]
----
include::../examples/InspectFull.mo[]
----

Note that, due to subtyping, all of the following variations, in order of increasing argument specificity, are legal definitions of `inspect_message`.

Blanket denial of all ingress messages, ignoring further information:

[source.no-repl,motoko]
----
include::../examples/InspectNone.mo[tag=inspect-none]
----

Declining anonymous calls:

[source.no-repl,motoko]
----
include::../examples/InspectCaller.mo[tag=inspect-caller]
----

Declining large messages, based on `arg`'s size (in bytes).

[source.no-repl,motoko]
----
include::../examples/InspectArg.mo[tag=inspect-arg]
----

Declining messages by name only, ignoring message arguments (note the use
of type `Any` as message argument variants):

[source.no-repl,motoko]
----
include::../examples/InspectName.mo[tag=inspect-name]
----

A combination of the previous three, specifying the argument types of some variants while ignoring others at type `Any` and using pattern matching to conflate identical cases.

[source.no-repl,motoko]
----
include::../examples/InspectMixed.mo[tag=inspect-mixed]
----

== Tips on authoring `inspect_message`

Implementing `inspect_message` after the fact, once all shared functions of an actor have already been implemented, can be tedious, since you'll need to declare a correctly typed
variant for public function.
A simple trick is to first implement the function _incorrectly_, with a `()` argument, compile the code, then use the compiler's error message
to obtain the required argument type.

For example, in the actor from the previous section, incorrectly declaring:

[source.no-repl,motoko]
----
include::../examples/InspectTrick.mo[tag=inspect-trick]
----

forces the compiler to cough up the expected type below:

[source.no-repl,motoko]
----
Inspect.mo:13.4-15.5: type error [M0127], system function inspect_message is declared with type
  () -> Bool
instead of expected type
  {
    arg : Blob;
    caller : Principal;
    msg :
      {
        #inc : () -> ();
        #read : () -> ();
        #reset : () -> ();
        #set : () -> Nat
      }
  } -> Bool
----

which you can now cut-and-paste into your code.