= Motoko Programming Language
:page-layout: default
:proglang: Motoko
:platform: Internet Computer blockchain network
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

TIP: The {proglang} programming language continues to evolve with each release of the {sdk-short-name} and with ongoing updates to the {proglang} compiler. Check back regularly to try new features and see what's changed.


The {proglang} programming language is a new, modern and type safe language for developers who want to build the next generation of distributed applications to run on the Internet Computer blockchain network.
{proglang} is specifically designed to support the unique features of the {IC} and to provide a familiar yet robust programming environment.
As a new language, {proglang} is constantly evolving with support for new features and other improvements.

The {proglang} compiler, documentation and other tooling is https://github.com/dfinity/motoko[open source] and released under the Apache 2.0 license. Contributions are welcome.

== Native canister smart contract support

{proglang} has native support for {IC} canister smart contracts.

A canister smart contract (or canister for short) is expressed as a {proglang} actor. An actor is an autonomous object that fully encapsulates its state and communicates with other actors only through asynchronous messages.

[source#counter,motoko]
----
include::../examples/Counter.mo[]
----

== Code sequentially in direct style

On the {IC}, canisters can communicate with other canisters by sending asynchronous messages.

Asynchronous programming is hard, so {proglang} enables you to author asynchronous code in much simpler, sequential style. Asynchronous messages are function calls that return a _future_, and the `await` construct allows you to suspend execution until a future has completed. This simple feature avoids the  "callback hell" of explicit asynchronous programming in other languages.

[source.include_counter,motoko]
----
include::../examples/factorial.mo[lines=9..-1]
----

== Modern type system

{proglang} has been designed to be intuitive to those familiar with JavaScript and other popular languages, but offers modern features such as sound structural types, generics, variant types, and statically checked pattern matching.

[source,motoko]
----
include::../examples/tree.mo[]
----

== Autogenerated IDL files

A {proglang} actor always presents a typed interface to its clients as a suite of named functions with argument and (future) result types.

The {proglang} compiler (and SDK) can emit this interface in a language neutral format called Candid, so other canisters, browser resident code and smart phone apps that support Candid can use the actor's services.
The {proglang} compiler can consume and produce Candid files, allowing {proglang} to seamlessly interact with canisters implemented in other programming languages (provided they support Candid).

For example, the previous {proglang} `+Counter+` actor has the following Candid interface:

[source,candid]
....
service Counter : {
  inc : () -> (nat);
}
....

[#orthogonal-persistence]
== Orthogonal persistence

The {IC} persists the memory and other state of your canister as it executes. Thus the state of a Motoko actor, including its in-memory data structures, survive indefinitely.
Actor state does not need to be explicitly "restored" and "saved" to external storage, with every message.

For example, in the following `Registry` actor (canister), that assigns sequential IDs to textual names, the state of the hash table is preserved across calls, even though the state of the actor
is replicated across many {IC} node machines, and typically not resident in memory.

[source,motoko]
----
include::../examples/Registry.mo[]
----

== Upgrades

{proglang} provides numerous features to help you leverage orthogonal persistence, including language features that allow you to retain a canister's data as you upgrade the code of the canister.

For example, {proglang} lets you declare certain variables as `stable`. The values of `stable` variables are automatically preserved across canister upgrades.

Consider a stable counter:

[source,motoko]
----
include::../examples/StableCounter.mo[]
----

It can be installed, incremented _n_ times, and then upgraded, without interruption, to, for example, the richer implementation:

[source,motoko]
----
include::../examples/StableCounterUpgrade.mo[]
----

Because `+value+` was declared `stable`, the current state, _n_, of the service is retained after the upgrade. Counting will continue from _n_, not restart
from `0`.

Because the new interface is compatible with the previous one, existing clients referencing the canister will continue to work, but new clients will be able to exploit its upgraded functionality
(the additional `reset` function).

For scenarios that can't be solved using stable variables alone, {proglang} provides user-definable upgrade hooks that run immediately before and after upgrade,
and allow you to migrate arbitrary state to stable variables.

== And more ...

{proglang} provides many other developer productivity features, including subtyping, arbitrary precision arithmetic and garbage collection.

{proglang} is not, and is not intended to be, the only language for implementing canister smart contracts.
If it doesn't suit your needs, there is a canister development kit (CDK) for the Rust programming language.
Our goal is to enable any language (with a compiler that targets WebAssembly) to be able to produce canister smart contracts that run on the {IC} and interoperate
with other, perhaps foreign, canister smart contracts through language neutral Candid interfaces.

Its tailored design means {proglang} should be the easiest and safest language for coding on the {IC}, at least for the forseeable future.

