= Upgrades, stable variables and upgrade methods


The {IC} lets you upgrade a deployed and running canister with a new
implementation, either to repair a bug or to add functionality. For a
stateful canister, upgrade is challenging as it requires the migration
of the canister's live state from the retired canister to its
replacement.  The traditional approach would be to either maintain the
state in a separate database, using some stable format, or evacuate
and reconstitute the state from a database, just before and after the
upgrade. To facilitate upgrades, without resorting to database or
external canisters, the {IC} allows a canister to save and restore
state from dedicated _stable_ storage that is retained across an
upgrade.


At a higher-level of abstraction, {proglang} provides language
support for using stable storage, automating the preservation of state
in a way that accommodates changes to both the data and the {proglang}
compiler version used to produce a canister's code.

The support relies on you - the programmer - anticipating and indicating
which data will require preservation. This may be some, none or all of an actor's state.

////
To enable {proglang} to migrate the current state of variables when a canister is upgraded, you must identify those variables as containing data that must be preserved.
////

In an actor, you can nominate a variable for stable storage by using the `+stable+` keyword - a modifier - in the variable's declaration.

More precisely, every `+let+` and `+var+` variable declaration in an actor can specify whether the variable is `+stable+` or `+flexible+`.
If you don't provide a modifier, the variable is declared as `+flexible+` by default.

////
Concretely, you use the following syntax to declare stable or flexible variables in an actor:

....
<dec-field> ::=
  (public|private)? (stable|flexible)? dec
....
////

For a simple example of declaring a stable counter,
that can be upgraded while preserving the counter's value, see
link:motoko{outfilesuffix}#upgrades[here].

////
The representation for stable variable signatures looks like a {proglang} actor type:

....
actor {
  stable x : Nat;
  stable var y : Int;
  stable z : [var Nat];
};
....
////

NOTE: you can only use the `+stable+` or `+flexible+` modifier on `let` and `var` declarations that are **actor fields**. You cannot use these modifiers anywhere else in your program.


== Typing

Because the compiler must ensure that stable variables are both compatible with and meaningful in the replacement program after an upgrade, the following type restrictions apply to stable state:

* every `+stable+` variable must have a _stable_ type

where a type is  _stable_ if it is:
* a _shared_ type; or
* an object type or array type with mutable fields or elements of stable type.

The only difference between stable and shared types is the former's support for mutation.
Like shared types, stable types are restricted to first-order data, excluding local functions and structures built from local functions (such as objects).
This exclusion of functions is required because the meaning of a function value—consisting of both data and code—cannot easily be preserved across an upgrade,
while the meaning of plain data—mutable or not—can be.

NOTE: In general, object types are not stable because they can contain local functions.
However, a plain record of stable data is a special case of object types that is stable.
Moreover, actors and shared functions are also stable, allowing you to preserve their values across upgrades.
For example, you can preserve state recording a set of actors or shared function callbacks subscribing to a service.

== How stable variables are upgraded

When you first compile and deploy an actor (canister), all flexible and stable variable are initialized in sequence.
When you deploy an actor (canister) as an upgrade, all stable variables that existed in the previous version are pre-initialized with their old values.
After the stable variables are initialized with their previous values, the remaining flexible and newly-added stable variables are initialized in sequence.

== System methods: `preupgrade()` and `postupgrade()`

Declaring a variable to be `+stable+` requires its type to be stable too.
Unfortunately, not all types are stable.
In particular, most object types are not stable, since objects are typically a mix of data members and function members and functions
are not stable.

As simple example, consider the `Registry` actor from link:motoko{outfilesuffix}[orthogonal_persistence].

[source,motoko]
----
include::../examples/Registry.mo[]
----

This actor assigns sequential identifiers to `Text` values, using the size of the underlying `map` object to determine the next identifier.
Like other actors, it relies on _orthogonal persistence_ to maintain the state of the hashmap between calls.

We'd like to make the `Register` upgradable, without the upgrade losing any existing registrations.

Unfortunately, its state, `map`, has a proper object type, that contains member functions (e.g. `map.get`), so the `map` variable cannot, itself, be declared `stable`.

For scenarios like this, that can't be solved using stable variables alone, {proglang} supports user-defined upgrade hooks that, when provided, run immediately before or after upgrade.
These allow you to migrate state between unrestricted flexible to more restricted stable variables.
These hooks are declared as `system` functions with special names, `preugrade` and `postupgrade`. Both functions must have type `: () -> ()`.

The `preupgrade` method lets you make a final update to stable variables, before the runtime commits their values to {IC} stable memory, and performs an upgrade.
The `postupgrade` method is run after an upgrade has initialized the replacement actor, including its stable variables, but before executing any shared function call (or message) on that actor.

Here, we introduce a new stable variable, `entries`, to save and restore the entries of the unstable hash table.

[source,motoko]
----
include::../examples/StableRegistry.mo[]
----

Note that the type of `entries`, being just an array of `Text` and `Nat` pairs, is indeed a stable type.

Our `preupgrade` system method simply writes the current `map` entries to `entries`, before `entries` is saved to stable memory.
Our `postupgrade` system method resets `entries` to the empty array, after `map` has been populated from `entries`, to free space.
