= Basic concepts and terms
:proglang: Motoko
:company-id: DFINITY

{proglang} is designed for distributed programming with actors.

Before you begin writing programs for distributed processing using actors, you should be familiar with a few of the basic building blocks of amy programming language and with {proglang} in particular. 
To get you started, this section introduces the following key concepts and terms that are used throughout the remainder of the documentation and that are essential to learning to program in {proglang}:

* program
* declaration
* expression
* value
* variable
* type

If you have experience programming in other languages or are familiar with <<modern-types,modern programming language theory>>, you are probably already comfortable with these terms and how they are used.
There's nothing unique in how these terms are used in {proglang}.
If you are new to programming, however, this guide introduces each of these terms gradually and by using simplified example programs that eschew any use of actors or distributed programming.
After you have the basic terminology as a foundation to build on, you can explore more advanced aspects of the language.
More advanced features are illustrated with correspondingly more complex examples.

The following topics are covered in the section:

 - <<intro-progs,Program syntax>>, and <<intro-full-syntax,full syntax overview>>
 - <<intro-printing,Printing numbers and text>>, and <<intro-stdlib, using the standard library>>
 - <<intro-decls-vs-exps,Declarations versus expressions>>
 - <<intro-lexical-scoping,Lexical scoping of variables>>
 - <<intro-values,Values and evaluation>>
 - <<intro-type-anno,Type annotations variables>>
 - <<intro-type-soundness,Type soundness and type-safe evaluation>>

[[intro-progs]]
== {proglang} programs

Each {proglang} _program_ is a free mix of declarations and expressions, whose syntactic classes are distinct, but related (see <<syntax, the appendix>> for precise program syntax).

For programs that we deploy on the Internet Computer, a valid program consists of an __actor expression__, introduced with specific syntax (keyword `actor`) that we discuss in
a <<chapter-actors,later chapter>>.

In preparing for that discussion, we discuss programs in this chapter and <<chapter-state,the next>> that are not meant to be Internet Computer services.
Rather, these tiny programs illustrate snippets of {proglang} for writing those services, and each can (usually) be run on its own as a (non-service) {proglang} program, possibly with some printed terminal output.

We begin with simple expressions, such as arithmetic.
We encourage advanced readers to skip around, and to use <<intro-full-syntax,this chart>> for a quick overview of the full (expression) syntax of {proglang}, with additional links and detailed definitions.

For other readers, we start slowly and move gradually.  The following snippet consists of two declarations (of variables `x` and `y`) followed by an expression, forming a single program:

....
let x = 1;
let y = x + 1;
x * y + x
....

We will use variations of this small program in our discussion below.

First, this program's type is `Nat` (natural number), and when run, it evaluates to the (natural number) value of `3`.

Introducing a block with enclosing braces (`{` and `}`) and another variable (`z`), we can amend our original program as follows:

....
let z = {
  let x = 1;
  let y = x + 1;
  x * y + x
};
printNat(z)
....

Before comparing declaration lists and expressions in more detail, we briefly digress to explain the `printNat` primitive, used in the final line above.

[[intro-printing]]
== Printing via `print` and `debug_show`

Above, we print the final value using the built-in function `printNat`:

....
printNat: Nat -> ()
....

The function `printNat` accepts a natural number value (of type `Nat`) as input, and produces the _unit value_ (of _unit type_, or `()`) as its output.

In a sense, there is no output.
The function `printNat` is impure, and rather than producing an output value, it produces the _effect_ of emitting the natural number in a human-readable form to the output terminal.
We discuss the return value (the unit value) <<intro-unit-type, in detail below>>, and relate it to the `void` type for readers more familiar with that concept.

Likewise, we can print text strings using `print`:

....
print: Text -> ()
....

So that the following program prints "hello world":

....
print("hello world")
....

Finally, we can transform most {proglang} values into human-readable text strings for debugging purposes, _without_ having to write those transformations by hand.

The `debug_show` primitive permits converting a large class of values into values of type `Text`.

For instance, we can convert a triple (of type `(Text, Nat, Text)`) into debugging text without writing a custom conversion function ourselves:

....
print(debug_show(("hello", 42, "world")))
....

Using these text transformations, we can print most {proglang} data as we experiment with our programs.

== Declarations and expressions

Declarations introduce immutable variables, mutable state, actors, objects, classes and other types.
Expressions describe computations that involve these notions.

For now, we use example programs that declare immutable variables, and compute simple arithmetic.

[[intro-decls-vs-exps]]
=== Declarations versus expressions

<<intro-progs,Recall>> that each {proglang} _program_ is a free mix of declarations and expressions, whose syntactic classes are distinct, but related.
In this section, we use examples to illustrate their distinctions and accommodate their intermixing.

Recall our example program, first introduced above:

....
let x = 1;
let y = x + 1;
x * y + x;
....

In reality, this program is a _declaration list_ that consists of _three_ declarations:

. immutable variable `x`, via declaration `let x = 1;`,
. immutable variable `y`, via declaration `let y = x + 1;`,
. and an _unnamed, implicit variable_ holding the final expression's value, `x * y + x`.

This expression `x * y + x` illustrates a more general principle:
//
Each expression can be thought of as a declaration where necessary since the language implicitly declares an unnamed variable with that expression's result value.

When the expression appears as the final declaration, this expression may have any type.  Here, the expression `x * y + x` has type `Nat`.

Expressions that do not appear at the end, but rather _within_ the list of declarations must have unit type, as with printing:

....
let x = 1;
printNat(x);
let y = x + 1;
printNat(y);
x * y + x;
....

=== Use `ignore` to place non-unit-typed expressions in declaration lists

We can always overcome this unit-type restriction by explicitly using `ignore` to ignore any unused result values:

....
let x = 1;
ignore(x + 42);
let y = x + 1;
ignore(y * 42);
x * y + x;
....

=== Declarations and variable substitution

Declarations may be mutually recursive, but in cases where they are not, they permit a substitution semantics.

Recall our original example:
....
let x = 1;
let y = x + 1;
x * y + x;
....

We may manually rewrite the program above by _substituting_ the variables' declared values for each of their respective occurrences.

In so doing, we produce the following expression, which is also a program:

....
1 * (1 + 1) + 1
....

This is also a valid program, of the same type and with the same behavior (result value) as the original program, `3`.

We can also form a single expression using a block.

=== From declarations to block expressions

Many of the programs above each consist of a list of declarations, as with this example, just above:

....
let x = 1;
let y = x + 1;
x * y + x
....

A declaration list is not itself (immediately) an _expression_, so we cannot (immediately) declare another variable with its final value (`3`).

[[intro-exp-block]]
**Block expressions.** We can form a _block expression_ from this list of declarations by enclosing it with matching _curly braces_:

....
{
  let x = 1;
  let y = x + 1;
  x * y + x
}
....

This is also program, but one where the declared variables `x` and `y` are privately scoped to the block we introduced.

This block form preserves the autonomy of the declaration list and its _choice of variable names_.

[[intro-lexical-scoping]]
=== Declarations follow *lexical scoping*

Above, we saw that nesting blocks preserves the autonomy of each separate declaration list and its _choice of variable names_.  Language theorists call this idea _lexical scoping_.
It means that variables' scopes may nest, but they may not interfere as they nest.

For instance, the following (larger, enclosing) program evaluates to `42`, _not_ `2`, since the final occurrences of `x` and `y`, on the final line, refer to the _very first_ definitions, _not_ the later ones within the enclosed block:

....
let x = 40; let y = 2;
{
  let x = 1;
  let y = x + 1;
  x * y + x
};
x + y
....

Other languages that lack lexical scoping may give a different meaning to this program.  However, modern languages universally favor lexical scoping, the meaning given here.

Aside from mathematical clarity, the chief practical benefit of lexical scoping is _security_, and its use in building compositionally-secure systems.
Specifically, {proglang} gives very strong composition properties: Nesting your program within one you do not trust cannot, for example, arbitrarily reassociate your variable
occurrences with different meanings.

[[intro-values]]
== Values and evaluation

Once a {proglang} expression receives the program's (single) thread of control, it evaluates eagerly until it reduces to a _(result) value_.

In so doing, it will generally pass control to sub-expressions, and to sub-routines before it gives up control from the _ambient control stack_.

If this expression never reaches a value form, the expression evaluates indefinitely.  Later we introduce recursive functions and imperative control flow, which each permit non-termination.
For now, we only consider terminating programs that result in values.

In the material above, we focused on expressions that produced natural numbers.
As a broader language overview, however, we briefly summarize the other value forms below:

=== Primitive values

{proglang} permits the following primitive value forms:

 - Boolean values (`true` and `false`).
 - Integers (...,`-2`, `-1`, `0`, `1`, `2`, ...); Bounded and _unbounded_ variants.
 - Natural numbers (`0`, `1`, `2`, ...); Bounded and _unbounded_ variants.
 - Text values --- strings of unicode characters.
 - Words --- fixed-width numbers, _without_ overflow checks, and _with_ explicit wrap-around semantics.

*Numbers.* By default, integers and natural numbers are _unbounded_ and do not overflow.  Instead, they use representations that grow to accommodate any finite number.

For practical reasons, {proglang} also includes _bounded_ types for integers and natural numbers, distinct from the default versions.
Each bounded variant has a fixed width (one of `8`, `16`, `32`, `64`) and each carries the potential for "`overflow`". If and when this event occurs, it is an error and causes the
<<overview-traps,program to trap>>.
There are no unchecked, uncaught overflows in {proglang}, except in well-defined situations, for specific (`Word`-based) types.

Word types permit bitwise operations that are unsupported by the other number types.  The language provides <<compiler-prelude-convert,primitive builtins to inter-convert between these various number representations>>.

The appendix contains a complete list of <<primitive-types,primitive types>>.

=== Non-primitive values

Building on the primitive values and types above, the language permits user-defined types, and each of the following non-primitive value forms and associated types:

 - <<tuples,Tuples>>, including the unit value (the "empty tuple")
 - <<exp-arrays, Arrays>>, with both _immutable_ and _mutable_ variants.
 - <<exp-object,Objects>>, with named, unordered fields and methods
 - <<variant-types,Variants>>, with named constructors and optional payload values
 - <<exp-func,Function values>>, including <<sharability,shareable functions>>.
 - <<exp-async,`async` values>>, also known as _promises_ or _futures_.
 - <<exp-error, `Error` values>> carry the payload of exceptions and system failures

We discuss the use of these forms in the succeeding chapters.

The links above give precise language definitions from the appendix.

[[intro-unit-type]]
=== The *unit type* versus the `void` type

{proglang} has no type named `void`.
In many cases where readers may think of return types being "`void`" from using languages like Java or C++, we encourage them to think instead of the _unit type_, written `()`.

In practical terms, like `void`, the unit value usually carries zero representation cost.

Unlike the `void` type, there _is_ a unit value, but like the `void` return value, the unit value carries no values internally, and as such, it always carries zero _information_.

Another mathematical way to think of the unit value is as a tuple with no elements---the nullary ("`zero-ary`") tuple. There is only one value with these properties, so it is mathematically unique, and thus need not be represented at runtime.

=== Natural numbers

The members of this type consist of the usual values ---`0`, `1`, `2`, ...----but, as in mathematics, the members of are not bound to a special maximum size.
Rather, the (runtime) representation of these values accommodates arbitrary-sized numbers, making their "overflow" (nearly) impossible.
(_nearly_ because it is the same event as running out of program memory, which can always happen for some programs in extreme situations).

{proglang} permits the usual arithmetic operations one would expect.
As an illustrative example, consider the following program:

....
let x = 42 + (1 * 37) / 12: Nat
....

This program evaluates to the value `45`, also of type `Nat`.

[[intro-type-soundness]]
== Type soundness

Each {proglang} expression that type-checks we call _well-typed_.  The _type_ of a {proglang} expression serves as a promise from the language to the developer about the future behavior of the program, if executed.

First, each well-typed program will evaluate without undefined behavior.
That is, the phrase **"`well-typed programs don't go wrong`"** applies here.
For those unfamiliar with the deeper implications of that phrase, it means that there is a precise space of meaningful (unambiguous) programs, and the type system enforces that we stay within it, and that all well-typed programs have a precise (unambiguous) meaning.

Furthermore, the types make a precise prediction over the program's result.
If it yields control, the program will generate a _(result) value_ that agrees with that of the original program.

In either case, the static and dynamic views of the program are linked by and agree with the static type system.
This agreement is the central principle of a static type system, and is delivered by {proglang} as a core aspect of its design.

The same type system also enforces that asynchrononous interactions agree between static and dynamic views of the program, and that the resulting messages generated "under the hood" never mismatch at runtime.
This agreement is similar in spirit to the caller/callee argument type and return type agreements that one ordinarily expects in a typed language.

[[intro-type-anno]]
== Type annotations and variables

Variables relate (static) names and (static) types with (dynamic) values that are present only at runtime.

In this sense, {proglang} types provide a form of _trusted, compiler-verified documentation_ in the program source code.

Consider this very short program:

....
let x : Nat = 1
....

In this example, the compiler infers that the expression `1` has type `Nat`, and that `x` has the same type.

In this case, we can omit this annotation without changing the meaning of the program:

....
let x = 1
....

Except for some esoteric situations involving operator overloading, type annotations do not (typically) affect the meaning of the program as it runs.

If they are omitted and the compiler accepts the program, as is the case above, the program has the same meaning (same _behavior_) as it did originally.

However, sometimes type annotations are required by the compiler to infer other assumptions, and to check the program as a whole.

When they are added and the compiler still accepts the program, we know that the added annotations are _consistent_ with the existing ones.

For instance, we can add additional (not required) annotations, and the compiler checks that all annotations and other inferred facts agree as a whole:

....
let x : Nat = 1 : Nat
....

If we were to try to do something _inconsistent_ with our annotation type, however, the type checker will signal an error.

Consider this program, which is not well-typed:

....
let x : Text = 1 + 1
....

The type annotation `Text` does not agree with the rest of the program, since the type of `1 + 1` is `Nat` and not `Text`, and these types are unrelated by subtyping.  Consequently, this program is not well-typed, and the compiler will signal an error (with a message and
location) and will not compile or execute it.

== Type errors and messages

Mathematically, the type system of {proglang} is _declarative_, meaning that it exists independently of any implementation, as a concept entirely in formal logic.
Likewise, the other key aspects of the language definition (for example, its execution semantics) exist outside of an implementation.

However, to design this logical definition, to experiment with it, and to practice making mistakes, we want to interact with this type system, and to make lots of harmless mistakes along the way.

The error messages of the _type checker_ attempt to help the developer when they misunderstand or otherwise misapply the logic of the type system, which is explained indirectly in this book.

These error messages will evolve over time, and for this reason, we will not include particular error messages in this text.
Instead, we will attempt to explain each code example in its surrounding prose.

[[intro-stdlib]]
=== Using the {proglang} standard library

For various practical language engineering reasons, the design of {proglang} strives to minimize builtin types and operations.

Instead, whenever possible, the {proglang} standard library provides the types and operations that make the language feel complete.
__**However**, this standard library is still under development,
and is still incomplete__.

An <<appendix-stdlib, appendix chapter>> lists a _selection_ of modules from the {proglang} standard library, focusing on core features used in the examples that are unlikely to change radically.
However, all of these standard library APIs will certainly change over time (to varying degrees), and in particular, they will grow in size and number.

To import from the standard library, use the `import` keyword.
Give a local module name to introduce, in this example `P` for "`**P**relude`", and a URL where the `import` declaration may locate the imported module:

....
import P "mo:stdlib/prelude";
P.printLn("hello world");
....

In this case, we import {proglang} code (not some other module form) with the `mo:` prefix.
We specify the `stdlib/` path, followed by the module's file name `prelude.mo` minus its extension.

=== Accommodating incomplete code

Sometimes, in the midst of writing a program, we want to run an incomplete version, or a version where one or more execution paths are either missing or simply invalid.

To accommodate these situations, we use the `xxx`, `nyi` and `unreachable` functions from the standard library, explained below.
Each wraps a <<overview-traps,general trap mechanism>>, explained further below.


=== Use short-term holes

Short-term holes are never committed to a source repository, and only ever exist in a single development session, for a developer that is still writing the program.

Assuming that earlier, one has imported the prelude as follows:

....
import P "mo:stdlib/prelude";
....

The developer can fill _any missing expression_ with the following one:

....
P.xxx()
....

The result will _always_ type check at compile time, and _will always_ trap at run time, if and when this expression ever executes.

=== Document longer-term holes

By convention, longer-term holes can be considered "yet not implemented" (`nyi`) features, and marked as such with a similar function from the prelude:

....
P.nyi()
....


=== Document `unreachable` code paths

In contrast to the situations above, sometimes code will _never_ be filled, since it will _never_ be evaluated, assuming the coherence of the internal logic of the programs' invariants.

To document a code path as logically impossible, or _unreachable_, use the standard library function `unreachable`:

....
P.unreachable()
....

As in the situations above, this function type-checks in all contexts, and when evaluated, traps in all contexts.

[[overview-traps]]
=== Execution traps stop the program

Each form above is a simple wrapper around the always-fail use of the <<exp-assert, `assert` primitive>>:

....
assert false
....

Dynamically, we call this program-halting behavior a _program(-generated) trap_, and we say that the program _traps_ when it executes this code.
It will cease to progress further.

[[intro-full-syntax]]
== Overview of program syntax

For reference information about {proglang} program syntax, see the xref:langauge-manual[Lanaguage manual] section and xref:language-manual{outfilesuffix}#syntax[Program syntax].