//! Static assertions to make sure object layouts are as expected

use crate::types::*;

use core::mem::size_of;

use static_assertions::const_assert_eq;

// Check platform word size
const_assert_eq!(size_of::<usize>(), size_of::<u32>());
const_assert_eq!(size_of::<usize>(), crate::constants::WORD_SIZE as usize);

// Check that sizes of structs are as expected by the compiler
const_assert_eq!(size_of::<Obj>(), 1 * size_of::<u32>());
const_assert_eq!(size_of::<ObjInd>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<Closure>(), 3 * size_of::<u32>());
const_assert_eq!(size_of::<Blob>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<BigInt>(), 5 * size_of::<u32>());
const_assert_eq!(size_of::<MutBox>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<Some>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<Variant>(), 3 * size_of::<u32>());
const_assert_eq!(size_of::<Concat>(), 4 * size_of::<u32>());
const_assert_eq!(size_of::<Null>(), 1 * size_of::<u32>());
const_assert_eq!(size_of::<Bits32>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<Bits64>(), 3 * size_of::<u32>());

// These aren't used generated by the compiler
const_assert_eq!(size_of::<OneWordFiller>(), 1 * size_of::<u32>());
const_assert_eq!(size_of::<FreeSpace>(), 2 * size_of::<u32>());
const_assert_eq!(size_of::<FwdPtr>(), 2 * size_of::<u32>());
