/* automatically generated by rust-bindgen 0.56.0 */

pub type mp_digit = u64;
pub type mp_sign = libc::c_int;
pub type mp_ord = libc::c_int;
pub type mp_err = libc::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mp_int {
    pub used: libc::c_int,
    pub alloc: libc::c_int,
    pub sign: mp_sign,
    pub dp: *mut mp_digit,
}
extern "C" {
    pub fn mp_init(a: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_zero(a: *mut mp_int);
}
extern "C" {
    pub fn mp_get_i32(a: *const mp_int) -> i32;
}
extern "C" {
    pub fn mp_set_i32(a: *mut mp_int, b: i32);
}
extern "C" {
    pub fn mp_set_u32(a: *mut mp_int, b: u32);
}
extern "C" {
    pub fn mp_get_i64(a: *const mp_int) -> i64;
}
extern "C" {
    pub fn mp_set_i64(a: *mut mp_int, b: i64);
}
extern "C" {
    pub fn mp_set_u64(a: *mut mp_int, b: u64);
}
extern "C" {
    pub fn mp_get_mag_u64(a: *const mp_int) -> u64;
}
extern "C" {
    pub fn mp_init_copy(a: *mut mp_int, b: *const mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_div_2d(a: *const mp_int, b: libc::c_int, c: *mut mp_int, d: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_mul_2d(a: *const mp_int, b: libc::c_int, c: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_2expt(a: *mut mp_int, b: libc::c_int) -> mp_err;
}
extern "C" {
    pub fn mp_neg(a: *const mp_int, b: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_abs(a: *const mp_int, b: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_cmp(a: *const mp_int, b: *const mp_int) -> mp_ord;
}
extern "C" {
    pub fn mp_add(a: *const mp_int, b: *const mp_int, c: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_sub(a: *const mp_int, b: *const mp_int, c: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_mul(a: *const mp_int, b: *const mp_int, c: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_div(a: *const mp_int, b: *const mp_int, c: *mut mp_int, d: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_incr(a: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_expt_u32(a: *const mp_int, b: u32, c: *mut mp_int) -> mp_err;
}
extern "C" {
    pub fn mp_count_bits(a: *const mp_int) -> libc::c_int;
}
