# This is a test blueprint workflow that will be called from
# test.yml, where the actual CI is invoked from.
# It will call the tests defined in the flake.nix file.
# These are: common-tests, gc-tests, and tests (debug, release)
# They all take the same install steps, use cachix, and a nix
# command like the following:
    # - run: nix profile install .#nix-build-uncached
    #   - name: "Run common tests"
    #     run: |
    #       cachix watch-exec ic-hs-test -- \
    #         nix-build-uncached --max-jobs auto \
    #           -E '(builtins.getFlake (toString ./.)).packages.${builtins.currentSystem}.common-tests'
    

# The main workflow from test.yml will call this workflow with different
# inputs, and this workflow will call the tests defined in the flake.nix file.


name: Test Blueprint

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: "OS to run tests on (ubuntu-latest, macos-13, ubuntu-24.04-arm, macos-latest)"
      test-target:
        required: true
        type: string
        description: "The test target to run (e.g. common-tests, gc-tests, release-systems-go, debug-systems-go)"
      test-name:
        required: true
        type: string
      ref:
        required: true
        type: string
        description: "The git ref to checkout (e.g. PR head SHA)"
      cachix-auth-token:
        required: true
        type: string
        description: "Cachix authentication token"

jobs:
  run-tests:
    name: ${{ inputs.test-name }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch full history so that git merge-base works
          fetch-depth: 0
          # fetch PR commit, not predicted merge commit
          ref: ${{ inputs.ref }}
      
      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: ic-hs-test
          authToken: ${{ inputs.cachix-auth-token }}

      - run: nix profile install .#nix-build-uncached

      - name: "Run ${{ inputs.test-name }}"
        run: |
          cachix watch-exec ic-hs-test -- \
          nix-build-uncached --max-jobs auto \
          -E '(builtins.getFlake (toString ./.)).packages.${builtins.currentSystem}.${{ inputs.test-target }}'