= Result module

The result of a computation that may contain errors, exceptions, etc.

Similar to the same concept of the same name in Rust. We use the Rust
nomenclature for the datatype and its constructors.

[source,motoko]
----
public type Result<Ok, Err> = {
  #ok: Ok;
  #err: Err;
};
----

== `assertUnwrap`

assert that we can unwrap the result; should only be used in tests, not
in canister implementations. This will trap.

[source,motoko]
----
public func assertUnwrap<Ok, Error>(r: Result<Ok, Error>) : Ok 
----

== `assertUnwrapAny`

[source,motoko]
----
public func assertUnwrapAny<Ok>(r: Result<Ok, Any>) : Ok
----

== `assertOk`

[source,motoko]
----
public func assertOk(r: Result<Any, Any>)
----

== `assertErr`

[source,motoko]
----
public func assertErr(r: Result<Any, Any>)
----

== `assertErrIs`

[source,motoko]
----
public func assertErrIs<E>(r: Result<Any, E>, f: E->Bool) : Bool
----

== `assertErrAs`

[source,motoko]
----
public func assertErrAs<E, X>(r:Result<Any, E>, f: E->X) : X
----

== `bind`

bind operation in result monad.

[source,motoko]
----
public func bind<R1, R2, Error>(
  x:Result<R1, Error>,
  y:R1 -> Result<R2, Error>) : Result<R2, Error>
----

== `mapOk`

map the `Ok` type/value, leaving any `Error` type/value unchanged.

[source,motoko]
----
public func mapOk<Ok1, Ok2, Error>(
  x: Result<Ok1, Error>,
  y: Ok1 -> Ok2) : Result<Ok2, Error>
----

== `fromOption`

create a result from an option, including an error value to handle the
`null` case.

[source,motoko]
----
public func fromOption<R, E>(x: ?R, err: E) : Result<R, E>
----

== `fromSomeMap`
map the `Ok` type/value from the optional value, or else use the given
error value.

[source,motoko]
----
public func fromSomeMap<R1, R2, E>(x: ?R1, f: R1->R2, err:E) : Result<R2, E>
----

== `fromSome`

asserts that the option is Some(_) form.

[source,motoko]
----
public func fromSome<Ok>(o: ?Ok) : Result<Ok, None>
----

== `joinArrayIfOk`

a result that consists of an array of Ok results from an array of
results, or the first error in the result array, if any.

[source,motoko]
----
public func joinArrayIfOk<R, E>(x: [Result<R, E>]) : Result<[R], E>
----