= Using the {proglang} standard library
:proglang: Motoko
:company-id: DFINITY

For various practical language engineering reasons, the design of {proglang} strives to minimize built-in types and operations.

Instead, whenever possible, the {proglang} standard library provides the types and operations that make the language feel complete.
__**However**, this standard library is still currently under development, and is still incomplete__.

This section describes a _selected subset_ of modules from the {proglang} standard library, with an emphasis on the modules that support core features and the libraries that are referenced in the examples.
The libraries documented in this section are the most stable and least likely to change.
However, all of the standard library APIs are subject to change over time to varying degrees.
You should note, in particular, that the size and number of modules and functions included in the standard library may increase dramatically as {proglang} evolves.

== Importing from the standard library

To import from the standard library, use the `import` keyword.
Give a local module name to introduce, in this example `P` for
"`**P**relude`", and a URL where the `import` declaration may locate
the imported module:

....
import P "mo:stdlib/prelude";
P.printLn("hello world");
....

This example illustrates how to import {proglang} code—indicated by using the `mo:` prefix—using the `stdlib/` standard library path and the module name `prelude`.
You can also import {proglang} code and other modules using relative paths.
For example, if you have created a {proglang} program named types.mo in the same folder as your main program, you could include it with an import declaration like this:

....
import Types "./types";
....

[[compiler-prelude]]
== Using predefined compiler prelude function

The compiler itself contains a *prelude* in every program, effectively extending the language definition with a set of types and declarations that are always available.

In addition to these built-in compiler definitions, the prelude of the standard library contributes some additional functions in a <<stdlib-prelude, supplemental `Prelude` module>>.

In contrast to the definitions in other modules, the compiler prelude definitions are always present, and do _not_ require any `import` declaration to bring them into the current scope.

include::compiler-prelude.adoc[]