#!/usr/bin/env python

import json
import sys
import os
import hashlib

source, checksum = sys.argv[1:3]

BLOCKSIZE=65536
crate_files = {}

for root, dirs, files in os.walk(source):
    for f in files:
        if f in ['.gitattributes', '.gitignore', '.cargo-ok', '.cargo-checksum.json', '.cargo_vcs_info.json']:
            continue
        if f.endswith('.rej') or f.endswith('.orig'):
            continue

        fpath = os.path.join(root, f)
        rpath = os.path.relpath(fpath, source)

        hasher = hashlib.sha256()
        with open(fpath, 'rb') as fp:
            buf = fp.read(BLOCKSIZE)
            while len(buf) > 0:
                hasher.update(buf)
                buf = fp.read(BLOCKSIZE)

        crate_files[rpath] = hasher.hexdigest()

output = {
  "files": crate_files,
  "package": checksum
}

out = json.dumps(output, separators=(',', ':'), sort_keys=True)

sys.stdout.write(out)

