#!/usr/bin/env python

import toml
import sys

source = sys.argv[1]

with open(source) as f:
    content = toml.load(f)

# first rewrite rust dependencies to make sure they are version pinned
for p in content['package']:
    if p.get('source') == 'registry+https://github.com/rust-lang/crates.io-index':
        print("https://crates.io/api/v1/crates/%s/%s/download %s-%s %s" % (p['name'], p['version'], p['name'], p['version'], p['checksum']))
